export default interface BondUser {
  id: number;
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  contactNumber: string;
  countryCode: string;
  details: any;
  secureId: string;
  verifiedAt: any;
  kycFinishedAt: any;
  createdAt: Date;
  updatedAt: Date;
  retryKyc: boolean;
  kycApprovedAt?: Date | null;
  putToDraftAt?: Date | null;
  kycApprovedBy?: number | null;
  kycVerifiedAt?: Date;
  kycVerifiedBy?: number;
  riskRating: string;
  blockLogin: boolean;
  blockWithdraw: boolean;
  blockTrade: boolean;
  generatedCsvReportAt: Date | null;
  deletedAt: Date;
  generatedInvestorCsvReportAt: Date;
  loginRetry: number;
  otpRetry: number;
  otpRequest: number;
  blockOtp: boolean;
  blockTxnOtp: boolean;
  blockRequireTxnOtp: boolean;
  txnOtpRetry: number;
  txnOtpRequest: number;
  blockRequireDeviceId: boolean;
  twoFaSecret?: string;
  twoFaEnabled?: boolean;
}
