version: 0.2
phases:
  install:
    commands:
      #  USED FOR SUBMODULES
      - echo "Nothing to do"

  pre_build:
    commands:
      - echo "Installing dependencies for PDAX auth service - `pwd`"
      - npm install
      - |
        if [ "$ENVIRONMENT" = "Dev" ]; then
            aws --region=ap-southeast-1 ssm send-command --instance-ids i-0422c5ad139d3124b --document-name pdax-migrate-db --parameters service=pdaxauth,branch=develop,workingDirectory=/home/ssm-user/pdax-auth-service,buildBucket=$BUILD_OUTPUT_BUCKET,region=ap-southeast-1,executionTimeout=3600
        elif [ "$ENVIRONMENT" = "Stage" ]; then
            aws --region=ap-southeast-1 ssm send-command --instance-ids i-0ef7bd857b456189a --document-name pdax-migrate-db --parameters service=pdaxauth,branch=stage,workingDirectory=/home/ssm-user/pdax-auth-service,buildBucket=$BUILD_OUTPUT_BUCKET,region=ap-southeast-1,executionTimeout=3600
        elif [ "$ENVIRONMENT" = "Prod" ]; then
            aws --region=ap-southeast-1 ssm send-command --instance-ids i-0798beeb6beb827df --document-name pdax-migrate-db --parameters service=pdaxauth,branch=master,workingDirectory=/home/ssm-user/pdax-auth-service,buildBucket=$BUILD_OUTPUT_BUCKET,region=ap-southeast-1,executionTimeout=3600
        fi
      - cd scripts/
      - pip3 install boto3
      - python3 generate_config.py
      - cd ..
      - echo "dependencies install completed `date`"

  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - node_modules/.bin/tsc
      - npm prune --production
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --s3-prefix $SERVICE --output-template-file app-output_sam.yaml

  post_build:
    commands:
      - echo "build completed on `date`"

artifacts:
  files:
    - app-output_sam.yaml
  discard-paths: yes
